config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: {
    sessions: 'users/sessions'
  }

  resources :feedbacks, only: [:new, :create]
  resources :badges, only: :index

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/admin.rb
class Admin < User
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :body, presence: true
  validate :validate_max_answers, on: :create

  belongs_to :question
  scope :correct, -> { where(correct: true) }

  private

  def validate_max_answers
    errors.add(:base, I18n.t('.limit_max_answers')) if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :badge_users, dependent: :destroy
  has_many :users, through: :badge_users

  validates :image, :name, :rule, :rule_parameter, presence: true
end

app/models/badge_user.rb
class BadgeUser < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true

  has_many :tests
  default_scope { order(title: :asc) }
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, presence: true

  belongs_to :test
  has_many :answers
  has_many :gists
end

app/models/test.rb
class Test < ApplicationRecord
  validates :title, presence: true
  validates :level, numericality: {
    only_integer: true, greater_than_or_equal_to: 0
  }
  validates :title, uniqueness: { scope: :level }

  belongs_to :category
  belongs_to :author, class_name: 'User'
  has_many :questions
  has_many :test_passages
  has_many :users, through: :test_passages

  scope :level, ->(level) { where(level: level) }
  scope :level_easy, -> { level(0..1) }
  scope :level_medium, -> { level(2..4) }
  scope :level_hard, -> { level(5..Float::INFINITY) }
  scope :by_category, lambda { |category_title|
    Test.joins('JOIN categories ON tests.category_id = categories.id')
        .where(categories: { title: category_title })
        .order(title: :DESC)
  }

  def self.category_by_title(category_title)
    Test.by_category(category_title).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_save :before_save_set_question
  before_update :before_update_check_timeleft
  before_update :before_update_test_passed

  scope :correct_passed_tests, ->(user) {
    user.test_passages.where(passed: true)
  }

  def test_passed?
    result_percent >= 85
  end

  def result_percent
    (100 * correct_questions) / test.questions.count
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    unless time_is_over?
      self.correct_questions += 1 if correct_answer?(answer_ids)
    end
    save!
  end

  def current_question_number
    test.questions.count - next_questions.count
  end

  def timer_seconds
    (expires_at - Time.now).to_i
  end

  private

  def expires_at
    created_at + test.timeleft.minutes
  end

  def time_is_over?
    expires_at < Time.now
  end

  def before_update_check_timeleft
    self.current_question = nil if time_is_over?
  end

  def before_update_test_passed
    self.passed = test_passed? if completed?
  end

  def before_save_set_question
    self.current_question = if completed?
                              test.questions.first
                            else
                              next_question
                            end
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count

    correct_answers_count == correct_answers.where(id: answer_ids).count &&
      correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    next_questions.first
  end

  def next_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  validates :first_name, :last_name, presence: true

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :authored_tests, class_name: 'Test', foreign_key: 'author_id'
  has_many :gists
  has_many :feedbacks
  has_many :badge_users
  has_many :badges, through: :badge_users

  def test_passage(test)
    test_passages.order(created_at: :desc).find_by(test_id: test.id)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    is_a?(Admin)
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badges_params)

    if @badge.save
      redirect_to admin_badges_path, notice: t('.success_create')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badges_params)
      redirect_to [:admin, @badge], notice: t('.success_update')
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path, notice: t('.success_destroy')
  end

  private

  def badges_params
    params.require(:badge).permit(:name, :image, :rule, :rule_parameter)
  end

  def set_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = current_user.badges
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :find_test, only: :start

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def rescue_with_test_not_found
    render plain: 'Ресурс не найден.'
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  ALERTS = { alert: 'danger', notice: 'primary' }.freeze

  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to repo, "https://github.com/#{author}/#{repo}", target: :blank
  end

  def alert_manager(key)
    ALERTS[key.to_sym] || key
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
  def gist_hash(url)
    /(?<=com\/).*/.match(url)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      t('.header_new', title: question.test.title)
    else
      t('.header_edit', title: question.test.title)
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_header(test)
    if test.new_record?
      t('.create_test')
    else
      t('.edit_test')
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= image_tag((badge.image), class: 'rounded-circle size-200px') %></td>
  <td><%= badge.name %></td>
  <td><%= link_to t('show'), admin_badge_path(badge) %></td>
  <td><%= link_to t('edit'), edit_admin_badge_path(badge) %></td>
  <td><%= link_to t('delete'), admin_badge_path(badge), method: :delete, data: { confirm: t('sure?') } %></td>
</tr>

app/views/admin/badges/_form.html.erb
<div class="row justify-content-center">
  <div class="col col-md-5">
    <%= render 'shared/errors', resource: @badge %>

    <%= form_with model: [:admin, @badge], local: true do |form| %>
      <div class="form-group">
      <p>
        <%= form.label :image %>
        <%= form.text_field :image, class: 'form-control'  %>
      </p>

      <p>
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control'  %>
      </p>

      <p>
        <%= form.label :rule %>
        <%= form.select :rule, options_for_select([
                                                    ['После прохождения всех тестов категории', 1],
                                                    ['После прохождения теста с первой попытки', 2],
                                                    ['После прохождения теста определенного уровня', 3]
                                                  ] , selected: @badge.rule), { prompt: true }, { class: 'form-control' } %>
      </p>

      <p>
        <%= form.label :rule_parameter %>
        <%= form.text_field :rule_parameter, class: 'form-control'  %>
      </p>

      <%= form.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
    <%= link_to t('back'), admin_tests_path %>
  </div>
</div>

app/views/admin/badges/edit.html.erb
<%= render 'form' %>

app/views/admin/badges/index.html.erb
<h1><%= t('.all_badges') %></h2>
<%= link_to t('.new_badge'), new_admin_badge_path, class: 'btn btn-primary' %>
<table class="table table-bordered mt-2">
  <thead>
    <tr>
      <th><%= t('.image') %></th>
      <th><%= t('.name') %></th>
      <th colspan="3"><%= t('.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @badges %>
  </tbody>
</table>

app/views/admin/badges/new.html.erb
<%= render 'form' %>

app/views/admin/badges/show.html.erb
<%= image_tag(@badge.image) %>
<p>
  <%= @badge.name %>
</p>

<p>
  <%= @badge.rule_parameter %>
</p>

<%= link_to t('edit'), edit_admin_badge_path(@badge) %> |
<%= link_to t('back'), admin_root_path %>

app/views/badges/_badge.html.erb
<tr>
  <td><%= image_tag((badge.image), class: 'rounded-circle size-200px') %></td>
  <td><%= badge.name %></td>
</tr>

app/views/badges/index.html.erb
<h1><%= t('.my_badges') %></h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= t('.image') %></th>
      <th><%= t('.name') %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @badges %>
  </tbody>
</table>