config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: {
    sessions: 'users/sessions'
  }

  resources :feedbacks, only: [:new, :create]
  resources :badges, only: :index

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/admin.rb
class Admin < User
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :body, presence: true
  validate :validate_max_answers, on: :create

  belongs_to :question
  scope :correct, -> { where(correct: true) }

  private

  def validate_max_answers
    errors.add(:base, I18n.t('.limit_max_answers')) if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :badge_users, dependent: :destroy
  has_many :users, through: :badge_users

  validates :image, :name, :rule, :rule_parameter, presence: true
end

app/models/badge_user.rb
class BadgeUser < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true

  has_many :tests
  default_scope { order(title: :asc) }
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, presence: true

  belongs_to :test
  has_many :answers
  has_many :gists
end

app/models/test.rb
class Test < ApplicationRecord
  validates :title, presence: true
  validates :level, numericality: {
    only_integer: true, greater_than_or_equal_to: 0
  }
  validates :title, uniqueness: { scope: :level }

  belongs_to :category
  belongs_to :author, class_name: 'User'
  has_many :questions
  has_many :test_passages
  has_many :users, through: :test_passages

  scope :level, ->(level) { where(level: level) }
  scope :level_easy, -> { level(0..1) }
  scope :level_medium, -> { level(2..4) }
  scope :level_hard, -> { level(5..Float::INFINITY) }
  scope :by_category, lambda { |category_title|
    Test.joins('JOIN categories ON tests.category_id = categories.id')
        .where(categories: { title: category_title })
        .order(title: :DESC)
  }

  def self.category_by_title(category_title)
    Test.by_category(category_title).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_save :before_save_set_question
  before_update :before_update_check_timeleft
  before_update :before_update_test_passed

  scope :correct_passed_tests, ->(user) {
    user.test_passages.where(passed: true)
  }

  def test_passed?
    result_percent >= 85
  end

  def result_percent
    (100 * correct_questions) / test.questions.count
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    unless time_is_over?
      self.correct_questions += 1 if correct_answer?(answer_ids)
    end
    save!
  end

  def current_question_number
    test.questions.count - next_questions.count
  end

  def timer_seconds
    (expires_at - Time.now).to_i
  end

  private

  def expires_at
    created_at + test.timeleft.minutes
  end

  def time_is_over?
    expires_at < Time.now
  end

  def before_update_check_timeleft
    self.current_question = nil if time_is_over?
  end

  def before_update_test_passed
    self.passed = test_passed? if completed?
  end

  def before_save_set_question
    self.current_question = if completed?
                              test.questions.first
                            else
                              next_question
                            end
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count

    correct_answers_count == correct_answers.where(id: answer_ids).count &&
      correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    next_questions.first
  end

  def next_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  validates :first_name, :last_name, presence: true

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :authored_tests, class_name: 'Test', foreign_key: 'author_id'
  has_many :gists
  has_many :feedbacks
  has_many :badge_users
  has_many :badges, through: :badge_users

  def test_passage(test)
    test_passages.order(created_at: :desc).find_by(test_id: test.id)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    is_a?(Admin)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
  def gist_hash(url)
    /(?<=com\/).*/.match(url)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      t('.header_new', title: question.test.title)
    else
      t('.header_edit', title: question.test.title)
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_header(test)
    if test.new_record?
      t('.create_test')
    else
      t('.edit_test')
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to t('.all_tests'), admin_tests_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Gists', admin_gists_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('.badges'), admin_badges_path, class: 'nav-link' %>
      </li>
    </ul>
    <% if signed_in? %>
      <p><%= t('.welcome_in', name: current_user.first_name) %> <%= link_to 'Guru', root_path %> | <%= link_to t('exit'), destroy_user_session_path, method: :delete %></p>
    <% else %>
      <%= link_to t('sign_up'), new_user_registration_path %> |
      <%= link_to t('login'), new_user_session_path %>
    <% end %>
  </div>
</nav>

app/views/layouts/_footer.html.erb
<footer>
  <p><%= current_year %> | Osman | <%= github_url('OnlyReFLeX', 'test-guru') %></p>
  <p><%= t('.info') %> | <%= link_to t('.feedback'), new_feedback_path %></p>
  <p><%= link_to t('.school_info'), 'http://thinknetica.com/', target: :_blank %></p>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to t('.all_tests'), tests_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('.my_badges'), badges_path, class: 'nav-link' %>
      </li>
      <% if current_user&.admin? %>
        <li class="nav-item">
          <%= link_to t('.admin_panel'), admin_root_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <% if signed_in? %>
      <p><%= t('.welcome_in', name: current_user.first_name) %> <%= link_to 'Guru', root_path %> | <%= link_to t('exit'), destroy_user_session_path, method: :delete %></p>
    <% else %>
      <%= link_to t('sign_up'), new_user_registration_path %> |
      <%= link_to t('login'), new_user_session_path %>
    <% end %>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= t('.html_title') %> | TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/navbar' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource&.errors.present? %>
  <%= content_tag :div, class: 'resource-errors alert alert-danger', data: { resource_id: resource.id } do %>
    <h4 class="alert-heading"><%= t('.header', count: resource.errors.count) %></h4>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :div, message, class: "alert alert-#{alert_manager(key)}", role: "alert" %>
<% end %>